/*
 * Prompt interpreter.
 *
 * Bridges the structured turn data produced by Rules with the template language implemented by Localization.
 *
 * The interpreter intentionally contains no game logic and no language-specific narration. It simply exposes a set of primitives that allow
 * localization templates to access the data generated by the rules engine.
 *
 * Each turn resolves to a sequence of segments ("text", "pause", or "input") rather than a single string. This is a superset of plain text,
 * not a separate mode: a turn with no pauses, breaks, or inputs resolves to a sequence containing exactly one text segment. Text segments are further
 * split automatically at sentence boundaries, and authors can force an additional split point with {Break} (e.g. around a long role list)
 * without introducing a pause. sequenceToText() derives flat narration text from a sequence, ignoring everything but "text" segments - used for the
 * manual script view, which never needs pause/input timing.
 *
 * Resolution happens in one of two modes, chosen per call via options.mode:
 *   - "manual" (default): every {Input:...} resolves straight to its manualKey, exactly as if it weren't there - the moderator-facing narration this
 *     produces never depends on anything not already known. Always resolved eagerly, in one batch (renderAll), since it has nothing to wait on.
 *   - "automatic": every {Input:...} instead becomes a real "input" segment - Choice inputs get every branch resolved eagerly, right here, before
 *     playback ever sees the node; Value inputs resolve their option labels eagerly but leave their continuation deferred until a real value is
 *     bound (see resolveDeferredInput). Because a later turn can depend on a value an earlier turn's input just bound (via options.boundValues,
 *     merged into that turn's data), automatic resolution has to happen turn-by-turn as playback reaches each one (resolveTurn), never as one
 *     upfront batch the way manual mode is.
 * {AutoKey:manualKey,autoKey} exists for content that needs to diverge between the two modes at a point deeper than a turn's own entry point
 * (_entryPointKey's PROMPT_AUTO_ fallback only ever fires once, before any resolving has started) - e.g. one arm of a Select needing an introductory
 * line for automatic playback that manual narration has no equivalent for.
 */

const Interpreter = (() => {

	/* =========================
	   Data
	   ========================= */

	// Named Pause presets, in seconds, with defaults overwritten from settings
	const PAUSE_LEVELS = {
		short: 10,
		medium: 20,
		long: 30,
	};

	// Global multiplier applied to every Pause duration, named or literal, so overall pacing can be tuned universally in one place. Overwritten from settings later.
	let PAUSE_SCALE = 1;

	// Delimiter used to wrap inline control markers (e.g. Pause, Break) within text resolved by Localization. Deliberately brace-free so _resolveTemplate never re-matches it, and built from a control character so it can never collide with authored narration text.
	const MARKER_DELIM = "\u0000";

	// Matches either marker kind in one pass so _toSequence can walk the resolved text with a single split(). The PAUSE branch's capture group is the only one in the pattern, so on a match it holds the pause duration string, or is undefined when a Break matched instead - that's how _toSequence tells the two kinds of marker apart.
	const CONTROL_MARKER = new RegExp(`${MARKER_DELIM}(?:PAUSE:([\\d.]+)|BREAK|INPUT:(\\d+))${MARKER_DELIM}`);

	// -- Template primitives --

	/*
	 * Template primitives available to localization strings.
	 *
	 * Each primitive receives the current turn's field bag together with the arguments supplied by the template expression and returns either:
	 *   - literal text
	 *   - another localization key to resolve
	 *
	 * Primitives are intentionally side-effect free and should contain only presentation logic. They exist only to assemble localization based on
	 * the data provided by the rules engine.
	 */
	const PRIMITIVES = {

		// {Identity:field[,form]} — field holds a ROLE_X/TEAM_X id (already prefixed by rules.js). form is "definite" | "plural" | "genitive" | omitted. Returns the localization key corresponding to the identity with applied form(s).
		Identity: (data, field, ...form) => {
			const id = data[field];
			if (id == null)
				throw new Error(`Identity: field '${field}' missing from turn data`);

			const key = _identityKey(id, form);
			if (key === null)
				throw new Error(`Identity: unrecognized form modifier(s) [${form.join(", ")}] on field '${field}'`);

			return key;
		},

		RoleName: (data, field, ...form) => {
			const role = data[field];
			if (role == null)
				throw new Error(`RoleName: field '${field}' missing from turn data`);

			const key = _identityKey(`ROLE_${role}`, form)
			if (key === null)
				throw new Error(`RoleName: unrecognized form modifier(s) [${form.join(", ")}] on field '${field}'`);

			return key
		},

		// Indirection allowing one role's prompt to reuse another role's action text.
		RoleAction: (data, field) => {
			const role = data[field];
			if (role == null)
				throw new Error(`RoleAction: field '${field}' missing from turn data`);

			return `{PROMPT_${role}_ACTION}`;
		},

		// {Value:field} — insert a scalar as-is. No lookup, no recursion.
		Value: (data, field) => {
			const v = data[field];
			if (v == null)
				throw new Error(`Value: field '${field}' missing from turn data`);

			return String(v);
		},

		// {LocalizedValue:field} - inserts a template tag that gets parsed
		LocalizedValue: (data, field) => {
			const v = data[field];
			return `{${v}}`;
		},

		// {IdentityList:field[,join]} — field holds an array of bare role ids (e.g. from ctx.getRolesPresentWithTag). Each element gets ROLE_-prefixed and resolved; join is "and" (default) or "or".
		IdentityList: (data, field, join = "and") => {
			const list = data[field];
			if (!Array.isArray(list))
				throw new Error(`IdentityList: list '${field}' is not an array`);
			if (list.length === 0)
				return "";

			return _joinList(list.map(id => `{ROLE_${id}}`), join);
		},

		// {ValueList:field[,join]} — field holds an array of display-ready values (e.g. player numbers). No per-item resolution, just joins.
		ValueList: (data, field, join = "and") => {
			const list = data[field];
			if (!Array.isArray(list))
				throw new Error(`ValueList: list '${field}' is not an array`);
			if (list.length === 0)
				return "";

			return _joinList(list.map(String), join);
		},

		// {If:field,key} — insert `key` iff data[field] is truthy, else nothing. Sugar over Select's two-arm case; kept separate because it's the overwhelmingly common case and reads better at the call site.
		If: (data, field, keyTrue, keyFalse) => {
			if (data[field]) return `{${keyTrue}}`;
			return keyFalse ? `{${keyFalse}}` : "";
		},

		// {Select:field,label,key,label,key,...,*,key} — match data[field] against each label (string-compared), "*" is the catch-all. Used for both type-based branching (Tier 4 outcomes) and grammatical selection (e.g. {Select:count,1,CARD_SINGULAR,*,CARD_PLURAL}).
		Select: (data, field, ...arms) => {
			const value = String(data[field]);
			for (let i = 0; i < arms.length; i += 2) {
				if (String(arms[i]) === value || arms[i] === "*")
					return `{${arms[i + 1]}}`;
			}
			throw new Error(`Select: no matching arm for field '${field}'='${value}' (no '*' catch-all provided)`);
		},

		/*
		 * {Pause:level|seconds} — narration-timing marker, not narration content. `level` is one of PAUSE_LEVELS' keys (a shared vocabulary
		 * for "how long does this kind of action take", so pause lengths stay consistent across roles and are tunable in one place rather than
		 * as scattered literals); a plain number is used as-is. Either way the result is scaled by a settings value before being embedded.
		 *
		 * Emits an inert sentinel (no braces, so _resolveTemplate never touches it again) that survives template resolution and Localization's
		 * own text cleanup untouched, then gets split back out by _toSequence once the turn's text is fully resolved. Has no effect on the flat
		 * script text - it's for the speech engine only. Intended for use inside PROMPT_ narration keys only; composing it into a key that's
		 * also reused outside Interpreter (e.g. via localizeStaticContent) would leak the raw marker into visible text.
		 */
		Pause: (data, level) => {
			const base = PAUSE_LEVELS[level] ?? Number(level);
			if (!Number.isFinite(base))
				throw new Error(`Pause: '${level}' is neither a known level (${Object.keys(PAUSE_LEVELS).join(", ")}) nor a number`);

			return `${MARKER_DELIM}PAUSE:${base * PAUSE_SCALE}${MARKER_DELIM}`;
		},

		/*
		 * {Break} — manual narration-split marker, not narration content. Splits what would otherwise be one text segment into two, with no
		 * pause between them. Sentences already split automatically (see _splitSentences); Break is for cutting a segment inside what would
		 * otherwise stay one sentence - e.g. before/after a long role list - so the TTS overlay never has to display more than one clause-ish
		 * chunk at a time.
		 *
		 * Like Pause, emits an inert brace-free sentinel that survives template resolution and Localization's cleanup untouched, then is
		 * consumed by _toSequence. Intended for use inside PROMPT_ narration keys only.
		 */
		Break: () => {
			return `${MARKER_DELIM}BREAK${MARKER_DELIM}`;
		},
	};



	/* =========================
	   Initialization
	   ========================= */

	function _init() {

	}

	_init();



	/* =========================
	   Private functions
	   ========================= */

	/*
	 * Builds the localization key for an identity (a ROLE_X or TEAM_X id) with the requested grammatical form(s) applied.
	 *
	 *   id   - the bare identity id, e.g. "ROLE_SEER" or "TEAM_WEREWOLF".
	 *   form - array of zero or more of "plural" | "definite" | "genitive", applied in that fixed order regardless of the array's own order.
	 *
	 * Returns the localization key wrapped in braces (e.g. "{ROLE_SEER_PLURAL_DEFINITE}"), ready to be re-resolved by _resolveTemplate.
	 * Returns null if form contains anything outside the three recognized values - the caller (Identity/RoleName) turns that into a thrown error.
	 */
	function _identityKey(id, form) {
		const known = new Set(["plural", "definite", "genitive"]);
		const bad = form.filter(f => !known.has(f));
		if (bad.length > 0) return null;

		let suffix = "";
		if (form.includes("plural")) suffix += "_PLURAL";
		if (form.includes("definite")) suffix += "_DEFINITE";
		if (form.includes("genitive")) suffix += "_GENITIVE";

		return `{${id}${suffix}}`;
	}

	/*
	 * Joins already-resolved-or-literal string fragments with LIST_AND/LIST_OR, matching however Localization's existing list-joining locale keys are shaped.
	 * items - array of strings to join; join - "and" (default elsewhere) or "or". Returns "" for an empty array, the sole item unchanged for
	 * a single-item array, and otherwise every item comma-joined except the last, which is joined via the LIST_AND/LIST_OR key.
	 */
	function _joinList(items, join) {
		if (items.length === 0) return "";
		if (items.length === 1) return items[0];

		const sepKey = join === "or" ? "LIST_OR" : "LIST_AND";
		if (items.length === 2)
			return `${items[0]} {${sepKey}} ${items[1]}`;

		return items.slice(0, -1).join(", ") + `, {${sepKey}} ` + items[items.length - 1];
	}

	/*
	 * Splits a resolved text chunk into one segment per sentence, on a period/question mark/exclamation mark followed by whitespace. Purely a
	 * display/pacing aid for the TTS overlay (otherwise long narration shows as one large block); has no effect on the flat script text, since
	 * sequenceToText() rejoins text segments with a single space regardless.
	 *
	 * Known limitation: this is a plain punctuation heuristic, not real sentence detection - a decimal number or abbreviation followed by a
	 * space (e.g. "3. 5") would be split too. Not a concern for the narration style used in PROMPT_ keys today, but worth knowing if that changes.
	 *
	 * text - the chunk to split (never contains control markers - see _toSequence, which only calls this on text between markers).
	 *
	 * Returns an array of trimmed, non-empty sentence strings (possibly empty if text is blank).
	 */
	function _splitSentences(text) {
		const trimmed = text.trim();
		if (!trimmed) return [];
		return trimmed.split(/(?<=[.?!])\s+/).map(s => s.trim()).filter(Boolean);
	}

	/*
	 * Splits fully-resolved text into text/pause/input segments. With two capture groups in CONTROL_MARKER (pause duration, input id), split()
	 * yields [textBefore, group1, group2] per match rather than the single interleaved pair the old PAUSE-only version handled - hence stepping
	 * by 3, not 2. Exactly one of the two groups is defined per match (or neither, for a Break, whose entire effect is the text/text split
	 * itself). sideTable resolves "INPUT:n" back to what the Input primitive captured during resolution; it's null in manual mode, where no
	 * INPUT marker is ever emitted in the first place.
	 *
	 *   text      - fully template-resolved text, still containing CONTROL_MARKER sentinels for any Pause/Break/Input it used.
	 *   sideTable - array of input-node data built up by _makeInputPrimitive during this same resolution pass, indexed by the marker's id; null
	 *               in manual mode.
	 *
	 * Returns the segment array: a mix of { type: "text", value }, { type: "pause", duration }, and (automatic mode only) input nodes as
	 * built by _buildInputNode.
	 */
	function _toSequence(text, sideTable) {
		const parts = text.split(CONTROL_MARKER);
		const seq = [];

		for (let i = 0; i < parts.length; i += 3) {
			for (const sentence of _splitSentences(parts[i]))
				seq.push({ type: "text", value: sentence });

			if (i + 1 >= parts.length) break; // trailing text chunk, no marker followed it

			const pauseDuration = parts[i + 1];
			const inputId = parts[i + 2];

			if (pauseDuration !== undefined)
				seq.push({ type: "pause", duration: Number(pauseDuration) });
			else if (inputId !== undefined)
				seq.push(_buildInputNode(sideTable[Number(inputId)]));
			// else: a Break matched - no segment of its own.
		}

		return seq;
	}

	/*
	 * Resolves a Pause `level` (a PAUSE_LEVELS key or a literal number) to a final duration in seconds, scaled by PAUSE_SCALE.
	 * Throws if level is neither. Used by both the Pause primitive and _makeInputPrimitive (an input's own timeoutSeconds).
	 */
	function _resolveDuration(level) {
		const base = PAUSE_LEVELS[level] ?? Number(level);
		if (!Number.isFinite(base))
			throw new Error(`Duration: '${level}' is neither a known pause level (${Object.keys(PAUSE_LEVELS).join(", ")}) nor a number`);
		return base * PAUSE_SCALE;
	}

	/*
	 * {AutoKey:manualKey,autoKey} — resolves to manualKey in manual mode, autoKey in automatic mode. Same purpose as _entryPointKey's
	 * PROMPT_AUTO_ fallback, but usable anywhere inside the template tree rather than only at a turn's own entry point - for content that
	 * diverges deep inside one Select arm (e.g. one outcome needs an introductory line for automatic playback that manual narration has no
	 * equivalent for), this avoids forking the entire parent template just to reach that one arm. Unlike Input, there's no hasKey fallback here -
	 * both keys are required arguments, same as Input's own manualKey - so there's nothing to guess by naming convention.
	 *
	 * mode - "manual" or "automatic", fixed at primitive-construction time (see _renderTurnSafe/_resolveAutomaticSequence).
	 *
	 * Returns the actual {AutoKey} primitive function: (data, manualKey, autoKey) => string.
	 */
	function _makeAutoKeyPrimitive(mode) {
		return mode === "automatic"
			? (data, manualKey, autoKey) => `{${autoKey}}`
			: (data, manualKey, autoKey) => `{${manualKey}}`;
	}

	/*
	 * The one primitive whose behavior depends on which resolution this call is for. Manual mode always has a self-contained manualKey to defer
	 * to, by convention - it ignores every other argument. Automatic mode never resolves anything here: it stashes the raw arguments and emits
	 * an inert marker (same idiom as Pause/Break), so _toSequence can turn it into a real node only once the surrounding text has finished
	 * resolving.
	 *
	 * Syntax: {Input:field,kind,manualKey,duration,defaultField,...rest}
	 *   choice: rest = value,label,continuationKey, value,label,continuationKey, ...
	 *   value:  rest = optionsField,continuationKey
	 * defaultField is always a data field name (never a literal), to stay consistent with how every other field-reference primitive works here -
	 * even a fixed design default (e.g. Oracle's force-ripple) has to arrive as a field so Input's grammar doesn't special-case by kind.
	 *
	 *   mode      - "manual" or "automatic", fixed at primitive-construction time.
	 *   sideTable - automatic mode only: the array this call's Input invocations push their captured data onto (mutated in place); ignored
	 *               (may be null) in manual mode.
	 *
	 * Returns the actual {Input} primitive function for the given mode.
	 */
	function _makeInputPrimitive(mode, sideTable) {
		if (mode === "manual")
			return (data, field, kind, manualKey) => `{${manualKey}}`;

		return (data, field, kind, manualKey, duration, defaultField, ...rest) => {
			const id = sideTable.length;
			sideTable.push({
				field,
				kind,
				timeoutSeconds: _resolveDuration(duration),
				defaultValue: data[defaultField],
				args: rest,
				baseData: data,
			});
			return `${MARKER_DELIM}INPUT:${id}${MARKER_DELIM}`;
		};
	}

	/*
	 * Error callback passed to Localization.localize() while resolving an input option's label. type/key match _resolveTemplate's onError
	 * contract; behaves like _strictTemplateError but without a turn to attribute the error to. Returns a visible "UNDEF: KEY" placeholder
	 * for a missing key; throws (rather than returning) on max_iterations, same asymmetry as _strictTemplateError.
	 */
	function _labelErrorHandler(type, key) {
		if (type === "max_iterations") throw new Error(`Input: max resolution iterations reached resolving label '${key}'`);
		console.warn(`Missing localization key: ${key} (input option label)`);
		return `UNDEF: ${key}`;
	}

	/*
	 * Turns one sideTable entry (captured by _makeInputPrimitive) into a real "input" segment, resolving whatever can be resolved eagerly
	 * for its kind - see the module comment's "automatic" mode description for why choice/value differ here.
	 *
	 *   entry - one sideTable element: { field, kind, timeoutSeconds, defaultValue, args, baseData }, as pushed by _makeInputPrimitive.
	 *
	 * Returns the input segment:
	 *   kind "choice" - { type: "input", field, timeoutSeconds, defaultValue, kind, options, branches }, with every branch's continuation
	 *                   already fully resolved into its own sequence via _resolveAutomaticSequence.
	 *   kind "value"  - { type: "input", field, timeoutSeconds, defaultValue, kind, options, deferred }, where deferred holds just enough
	 *                   (key, field, baseData) for resolveDeferredInput to resolve the continuation later, once a real value is bound.
	 *
	 * Throws for an unrecognized kind, or (kind "value") if the referenced options field isn't an array.
	 */
	function _buildInputNode(entry) {
		const { field, kind, timeoutSeconds, defaultValue, args, baseData } = entry;
		const base = { type: "input", field, timeoutSeconds, defaultValue };

		if (kind === "choice") {
			const options = [];
			const branches = {};
			for (let i = 0; i < args.length; i += 3) {
				const [value, label, continuationKey] = args.slice(i, i + 3);
				options.push({ value, label: Localization.localize(label, PRIMITIVES, baseData, _labelErrorHandler) });
				branches[value] = _resolveAutomaticSequence(continuationKey, { ...baseData, [field]: value });
			}
			return { ...base, kind, options, branches };
		}

		if (kind === "value") {
			const [optionsField, continuationKey] = args;
			const rawOptions = baseData[optionsField];
			if (!Array.isArray(rawOptions))
				throw new Error(`Input: options field '${optionsField}' is not an array`);

			const options = rawOptions.map(o => ({
				value: o.value,
				label: Localization.localize(o.label, PRIMITIVES, baseData, _labelErrorHandler),
			}));
			return { ...base, kind, options, deferred: { key: continuationKey, field, baseData } };
		}

		throw new Error(`Input: unrecognized kind '${kind}'`);
	}

	/*
	 * Maps a turn action to its corresponding prompt template as an entry point for the parsing.
	 * action - the turn's action id; verbosity - "verbose" | "brief" (manual mode only); mode - "manual" | "automatic".
	 * Returns the localization key to start resolving from: PROMPT_AUTO_<action> if it exists (falling back to PROMPT_<action>) in
	 * automatic mode, else PROMPT_<action> or PROMPT_BRIEF_<action> depending on verbosity.
	 */
	function _entryPointKey(action, verbosity, mode) {
		if (mode === "automatic") {
			const autoKey = `PROMPT_AUTO_${action}`;
			return Localization.hasKey(autoKey) ? autoKey : `PROMPT_${action}`;
		}
		return `PROMPT${verbosity === "brief" ? "_BRIEF_" : "_"}${action}`;
	}

	/*
	 * Error callback passed to Localization.localize() for a given turn.
	 *
	 * The two error types are handled asymmetrically on purpose: a missing localization key is treated as recoverable (logged, rendered as a
	 * visible "UNDEF: KEY" placeholder) so one absent translation doesn't take down the whole turn's narration. Hitting the max resolution
	 * iteration count instead means the template is very likely cyclic and unrecoverable, so it throws — which _renderTurnSafe below catches and
	 * converts into a per-turn error rather than a placeholder.
	 *
	 *   turn - the turn being rendered, used only to attribute a log message/thrown error to its action/instigator.
	 *
	 * Returns the actual onError callback: (type, key) => string, matching _resolveTemplate's contract.
	 */
	function _strictTemplateError(turn) {
		return (type, key) => {
			if (type === "max_iterations")
				throw new Error(`_resolveTemplate: max resolution iterations reached for '${turn.action}', '${turn.instigator}'`);

			console.warn(`Missing localization key: ${key} (action=${turn.action}, instigator=${turn.instigator})`);
			return `UNDEF: ${key}`;
		};
	}

	/*
	 * Builds the visible diagnostic text shown in place of a turn that failed to render, and logs the underlying error to the console.
	 *   turn - a turn carrying an `error` (either one Rules attached, or one caught during rendering here). Returns the diagnostic string.
	 */
	function _formatErrorText(turn) {
		const detail = turn.error?.message ?? String(turn.error);
		console.error(`Failed to render turn (action=${turn.action}, instigator=${turn.instigator}):`, turn.error);
		return `⚠ COULD NOT RENDER [${turn.action ?? "?"} / ${turn.instigator ?? "?"}]: ${detail}`;
	}

	/*
	 * Wraps a diagnostic string as a single-segment sequence, so callers of renderAll never need to special-case the error path just because
	 * it didn't come from _toSequence. Returns [{ type: "text", value: text }].
	 */
	function _errorSequence(text) {
		return [{ type: "text", value: text }];
	}

	/*
	 * Resolves a single turn into localized narration while converting any rendering failures into user-visible diagnostics.
	 *
	 *   turn    - the turn to render: { action, instigator, data } normally, or { action, instigator, error } if Rules already failed to
	 *             build it (that error is surfaced as-is, without attempting to render).
	 *   options - { mode = "manual", verbosity = "verbose", boundValues = {} }; boundValues is merged under turn.data, so a value
	 *             set there can still be overridden by the turn's own data.
	 *
	 * Returns { sequence, error }. error is null on success; on any failure (a pre-existing turn.error, or an exception thrown while
	 * resolving) sequence instead holds a single diagnostic text segment describing the failure (see _formatErrorText).
	 */
	function _renderTurnSafe(turn, options) {
		if (turn.error)
			return { sequence: _errorSequence(_formatErrorText(turn)), error: turn.error };

		const verbosity = options.verbosity ?? "verbose";
		const mode = options.mode ?? "manual";
		const boundValues = options.boundValues ?? {};
		const data = { ...boundValues, ...turn.data, action: turn.action, instigator: turn.instigator };
		const entryKey = _entryPointKey(turn.action, verbosity, mode);

		try {
			if (mode === "automatic")
				return { sequence: _resolveAutomaticSequence(entryKey, data), error: null };

			const primitives = { ...PRIMITIVES, Input: _makeInputPrimitive("manual", null), AutoKey: _makeAutoKeyPrimitive("manual") };
			const resolved = Localization.localize(entryKey, primitives, data, _strictTemplateError(turn));
			return { sequence: _toSequence(resolved, null), error: null };
		} catch (error) {
			return { sequence: _errorSequence(_formatErrorText({ ...turn, error })), error: error };
		}
	}

	/*
	 * Resolves one localization key into an automatic-mode sequence, with its own fresh sideTable and Input/AutoKey primitives - used both
	 * for a turn's top-level entry key (_renderTurnSafe) and for a Choice input's branch continuations (_buildInputNode).
	 *   key  - the localization key to resolve.
	 *   data - the field bag available to the template (turn data plus any boundValues already merged in by the caller).
	 * Returns the resulting segment sequence (see _toSequence). A missing key here is non-fatal (logged, rendered as "UNDEF: KEY"); hitting
	 * the max iteration count throws, same as everywhere else template resolution can cycle.
	 */
	function _resolveAutomaticSequence(key, data) {
		const sideTable = [];
		const primitives = { ...PRIMITIVES, Input: _makeInputPrimitive("automatic", sideTable), AutoKey: _makeAutoKeyPrimitive("automatic") };
		const resolved = Localization.localize(key, primitives, data, (type, k) => {
			if (type === "max_iterations")
				throw new Error(`_resolveTemplate: max resolution iterations reached for '${key}'`);
			console.warn(`Missing localization key: ${k}`);
			return `UNDEF: ${k}`;
		});
		return _toSequence(resolved, sideTable);
	}
	
	
	
	/* =========================
	   Public functions
	   ========================= */

	/*
	 * Flattens a sequence back down to plain text, ignoring non-text segments (pauses, and any future control segment types). This is the single
	 * place that defines what "the script" means in terms of a sequence, so GUI and any other flat-text consumer derive it here rather than
	 * duplicating the join logic - or worse, drifting from it.
	 *
	 * sequence - a segment array as produced by resolveTurn/renderAll. Returns the joined text, space-separated between segments.
	 */
	function sequenceToText(sequence) {
		//return sequence.filter(s => s.type === "text" || s.type == "pause").map(s => s.value || "<PAUSE:"+s.duration+">").join(" ");
		return sequence.filter(s => s.type === "text").map(s => s.value).join(" ");
	}

	/*
	 * Refreshes pause timing from Settings. Only meaningful for automatic narration - pause segments carry duration but never surface in
	 * sequenceToText(), so the manual text script is unaffected regardless of when (or whether) this is called. Snapshotted once per
	 * narration session rather than kept live, so a settings change mid-playback intentionally doesn't retime a session already underway.
	 *
	 * No parameters. No return value - updates the module-level PAUSE_SCALE/PAUSE_LEVELS in place.
	 */
	function refreshPauseSettings() {
		PAUSE_SCALE = Settings.getValue("narration.pause_scale") ?? PAUSE_SCALE;
		PAUSE_LEVELS.short = Settings.getValue("narration.pause_short") ?? PAUSE_LEVELS.short;
		PAUSE_LEVELS.medium = Settings.getValue("narration.pause_medium") ?? PAUSE_LEVELS.medium;
		PAUSE_LEVELS.long = Settings.getValue("narration.pause_long") ?? PAUSE_LEVELS.long;
	}

	/*
	 * Resolves every turn in one batch via resolveTurn (see below for per-turn behavior).
	 *
	 *   turns   - array of Rules-produced turns.
	 *   options - forwarded unchanged to resolveTurn for every turn.
	 *
	 * Returns an array of { action, instigator, sequence, error }, one per input turn, in the same order.
	 */
	function renderAll(turns, options = {}) {
		return turns.map(turn => resolveTurn(turn, options));
	}

	/*
	 * Resolves a single turn into localized narration, isolating any rendering failure to just this turn so one malformed template never
	 * prevents the rest of the narration from being generated (see _renderTurnSafe).
	 *
	 *   turn    - one Rules-produced turn: { action, instigator, data } or, for a turn Rules itself failed to build, { action, instigator, error }.
	 *   options - { mode = "manual", verbosity = "verbose", boundValues = {} }, forwarded to _renderTurnSafe unchanged.
	 *
	 * Returns { action, instigator, sequence, error }. error is null on success; sequence always contains at least a diagnostic text
	 * segment even on failure, so callers can render *something* for a turn without checking error first.
	 */
	function resolveTurn(turn, options = {}) {
		const { sequence, error } = _renderTurnSafe(turn, options);
		return { action: turn.action, instigator: turn.instigator, sequence, error };
	}

	/*
	 * Resolves a Value-kind input's continuation once its field is finally bound - by a real selection or by its own default, decided entirely by
	 * the narration controller. Never called for Choice inputs, whose branches were already fully resolved inside _buildInputNode.
	 *
	 *   deferred   - the { key, field, baseData } stashed by _buildInputNode for this input.
	 *   boundValue - the value that ended up bound to deferred.field (selected, or defaulted).
	 *
	 * Returns the resulting segment sequence (see _resolveAutomaticSequence).
	 */
	function resolveDeferredInput(deferred, boundValue) {
		return _resolveAutomaticSequence(deferred.key, { ...deferred.baseData, [deferred.field]: boundValue });
	}



	return {
		renderAll,
		resolveTurn,
		resolveDeferredInput,
		sequenceToText,
		refreshPauseSettings,
	};

})();